/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as CertificateCertificateNumberRouteImport } from './routes/certificate.$certificateNumber'
import { Route as VerifyIndexRouteImport } from './routes/verify.index'
import { Route as VerifyCertificateNumberRouteImport } from './routes/verify.$certificateNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateCertificateNumberRoute =
  CertificateCertificateNumberRouteImport.update({
    id: '/certificate/$certificateNumber',
    path: '/certificate/$certificateNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const VerifyIndexRoute = VerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateNumberRoute = VerifyCertificateNumberRouteImport.update({
  id: '/verify/$certificateNumber',
  path: '/verify/$certificateNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/citizen': typeof CitizenRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRoute
  '/certificate/$certificateNumber': typeof CertificateCertificateNumberRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/citizen': typeof CitizenRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRoute
  '/certificate/$certificateNumber': typeof CertificateCertificateNumberRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/verify': typeof VerifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/citizen': typeof CitizenRoute
  '/login': typeof LoginRoute
  '/officer': typeof OfficerRoute
  '/certificate/$certificateNumber': typeof CertificateCertificateNumberRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/verify/': typeof VerifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/citizen'
    | '/login'
    | '/officer'
    | '/certificate/$certificateNumber'
    | '/verify/$certificateNumber'
    | '/verify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/citizen'
    | '/login'
    | '/officer'
    | '/certificate/$certificateNumber'
    | '/verify/$certificateNumber'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/citizen'
    | '/login'
    | '/officer'
    | '/certificate/$certificateNumber'
    | '/verify/$certificateNumber'
    | '/verify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CitizenRoute: typeof CitizenRoute
  LoginRoute: typeof LoginRoute
  OfficerRoute: typeof OfficerRoute
  CertificateCertificateNumberRoute: typeof CertificateCertificateNumberRoute
  VerifyCertificateNumberRoute: typeof VerifyCertificateNumberRoute
  VerifyIndexRoute: typeof VerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$certificateNumber': {
      id: '/certificate/$certificateNumber'
      path: '/certificate/$certificateNumber'
      fullPath: '/certificate/$certificateNumber'
      preLoaderRoute: typeof CertificateCertificateNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/': {
      id: '/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof VerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateNumber': {
      id: '/verify/$certificateNumber'
      path: '/verify/$certificateNumber'
      fullPath: '/verify/$certificateNumber'
      preLoaderRoute: typeof VerifyCertificateNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CitizenRoute: CitizenRoute,
  LoginRoute: LoginRoute,
  OfficerRoute: OfficerRoute,
  CertificateCertificateNumberRoute: CertificateCertificateNumberRoute,
  VerifyCertificateNumberRoute: VerifyCertificateNumberRoute,
  VerifyIndexRoute: VerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
